apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: po-generator
  labels:
    app.kubernetes.io/name: po-generator
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
